FROM node:21-alpine
WORKDIR /app
COPY package.json ./
RUN npm i
COPY . .
CMD ["npx", "ts-node", "./src/index.ts"]
EXPOSE 4000

# BUILD
# docker build . -f Dockerfile.dev -t label_detector:dev

# RUN
# docker run -d -p 4000:4000 --name label_detector_dev label_detector:dev
